### ISSUE TITLE
Odd behaviour with msg.sender

### ISSUE THREAD

**Issue by mrwillis** [optionality/clone-factory#12]
Hi,

I'm not sure if this is actually a bug or just a consequence of this technique. I ran into this using `Ownable` contracts in that when the master is cloned, `msg.sender` is simply `0x0`. I've reproduced it using this repo setting `owner = msg.sender` in the constructor. I would think that `msg.sender` would be the address of the `DummyFactory`.

Any ideas?

Thanks again!

https://github.com/mrwillis/clone-factory-repro

**Comment by flygoing** [comment]
@mrwillis This doesn't work because the constructor isn't called on the clones. The clone is just the 50-some-odd bytes in the factory contract, and all you're doing when you create the clone is creating a contract with those bytes. If you want to run something (like stuff you would put in the constructor) on creation of the clone, you would want to put it in the `init` function.

**Comment by mrwillis** [comment]
Got it. Thanks!
