### ISSUE TITLE
Use in production?

### ISSUE THREAD

**Issue by glitch003** [optionality/clone-factory#15]
Hi, apologies for raising a github issue for what is certainly just an informational question.

Is anyone that you know of using this in production on the mainnet?  We are considering using this as part of a dApp we're building and would love to know if it's "battle tested" in production anywhere.

This is a really amazing and much needed piece of infrastructure to provide for the eth ecosystem, so thank you.  I appreciate your efforts to get this standardized via EIP 1167.

**Comment by flygoing** [comment]
The only one I *know* of is https://finneyvote.com/, although there may be others that we don't know about. In a sense, I'm glad that there hasn't been heavy mainnet usage since the proxy bytecode has changed a bit through the months, and anybody running on mainnet on an old version wouldn't benefit from the EIP. There are a few people using clone-factory in development as well, notably Chronologic in their revamp of ethereum-alarm-clock.

**Comment by glitch003** [comment]
Awesome, thanks for the info!

**Comment by mds1** [comment]
>  In a sense, I'm glad that there hasn't been heavy mainnet usage since the proxy bytecode has changed a bit through the months, and anybody running on mainnet on an old version wouldn't benefit from the EIP. 

@flygoing Could you expand on what you mean by this? I was planning to leverage the `createClone ` function of `CloneFactory.sol` on mainnet, though this statement makes me hesitant. I came across this repo through the recent OpenZeppelin [article](https://blog.openzeppelin.com/deep-dive-into-the-minimal-proxy-contract/) on EIP 1167, so figured it would be safe to use. Are there any concerns to be aware of?

**Comment by nateawelch** [comment]
@mds1 Sorry for the delay, I'm infrequent to check my Github notifications. My now 1.5 year old comment was referring to the fact that the minimal proxy bytecode that clone-factory relies on (EIP 1167), which we also wrote, hadn't been standardized yet, and prior to standardization the bytecode was constantly being golfed/optimized. It is now stable since the EIP was finalized, and the bytecode used in this library wont change from the bytecode in the EIP. There are no further concerns regarding this.

The list of production implementations is also longer now. My current company Totle uses these in production to handle the creation of affiliate contracts, Augur v2 uses them, and Chronologic has been using them in production for some time now. There are others as well, but I don't have an extensive list.

**Comment by mds1** [comment]
@flygoing Hey, no worries at all. Appreciate the response. I was just trying to do some due diligence and make sure there was nothing major I was missing. Did some tests with the OpenZeppelin implementation and had no problems with it, so ended up moving forward with that.
