### ISSUE TITLE
How would one update the address the proxy is using?

### ISSUE THREAD

**Issue by zeekay** [optionality/clone-factory#7]
It'd be really useful to be able to update the address the proxy uses after the fact (to upgrade underlying contract code). How would one go about that? Extend the contract template with some asm to define a method to update the address? Presumably this would make the clones a bit larger, once you take into consideration security considerations. 

Is this feasible, and/or could you provide some guidance for how I'd add support for that?

**Comment by yarrumretep** [comment]
Hi Zach,  yeah - that would be a whole 'nother thing.  Likely, to upgrade you would need proxy local logic to run governance of the upgrade (could just be isOwner check) and set the new delegate address.  This project is really focused on a clone contract that effectively copies the logic of the master contract verbatim - thus (a) keeping it super inexpensive to deploy / operate and (b) very simple and robust representation to readers / users - that this contract location will always implement the code at the destination.

You could certainly implement an upgradable contract as the target of the clones - and thus achieve group upgradability of all of the clones (with whatever governance of that you wanted to implement).

What you are proposing is possible, of course, just not within the scope of this project.  Happy to discuss further if you'd like, but for now I'll close this issue.

**Comment by flygoing** [comment]
@zeekay You can use the returndatasize opcode to get the size of the return data from the last delegatecall. I think your upgradability would be fairly easily implemented by editing the shim contract assembly to have the target contract address be in storage instead of hardcoded in bytecode and have the master contract have code to update the target address. This would of course mean the shim contract would only be upgradable using the code in the master contract, and if you somehow messed up the upgradability of the new master, then you're SOL.

**Comment by flygoing** [comment]
@yarrumretep I think we should actually consider creating a version that's upgradable in some fashion either through what I just described or some other mechanism

**Comment by zeekay** [comment]
@flygoing something like:

```function() payable {
    // Require successfull delegate call 
    require(currentVersion.delegatecall(msg.data));
    assembly {
        let outsize := returndatasize 
        let outptr := mload(0x40) // Load memory
        mstore(0x40, add(outptr, outsize)) // Load up to return size
        returndatacopy(outptr, 0, outsize) // Copy last return into pointer
        return(outptr, outsize) 
    }
}```

**Comment by yarrumretep** [comment]
@zeekay - that looks about right. Unless you have other code in the contract that calls this default function, you don't have to bother with the 0x40 memory management pieces.  Memory is a clean slate for each call, delegatecall, staticcall etc.

**Comment by zeekay** [comment]
Perfect, thanks a lot ya'll :) 

Ever available for some freelance hacking? I'd love to chat: zach@hanzo.ai.

**Comment by yarrumretep** [comment]
@zeekay - @flygoing is right that you needn't have the logic for changing / governing the `currentVersion` variable in the proxy contract itself.  It can (should) be in the master contracts where it will serve the dual purpose of making sure the master contract's state does not stomp on the `currentVersion` slot. 

Also, do you want to upgrade each clone independently - or do you want to upgrade the whole fleet in one go?

**Comment by zeekay** [comment]
Oh, definitely want to upgrade all fleet in one go. That's the rough architecture I came up with when I ran into your library last night :)

**Comment by yarrumretep** [comment]
@zeekay - it turns out there isn't a simple way to do an upgrade-in-one-go fleet of clones.  Because every handoff to the master contract is a delegatecall, the storage of the called contract is the leaf contract's storage.  Even with a double-delegation model, you still have to upgrade each leaf independently.

If you really want to upgrade the fleet in one go, the clone contract will need to call out to a separate contract to fetch the 'currentVersion' address.  Adding an additional call to every call and a bit more complexity to the architecture.  Does that make sense?  Reach out to me on gitter if you want to chat more 'realtime'

**Comment by JarenL** [comment]
@zeekay @yarrumretep Hey guys stumbling upon this thread a little late. I think i have the exact same question revolving how to make the CloneFactory upgradeable, specifically how to upgrade a fleet already deployed with CloneFactory. Did you guys figure out an implementation?
