### ISSUE TITLE
Implementation on Rinkeby

### ISSUE THREAD

**Issue by genkifs** [optionality/clone-factory#8]
Straight implementation of this code on rinkeby, called the function createThing("Slave",1) and got this transaction
https://rinkeby.etherscan.io/tx/0xa474603e50c73cdec5cfb6f7d30c30002fd1a93517d55c1e738ca53ac9a3ab98

Unfortunately, there doesn't seem to be any new contract created at the address emitted by the event.  
https://rinkeby.etherscan.io/address/0x142e5ee03a46239a21a47ff4801e0889e6889116

I used remix to create the contracts, but that shouldn't be an issue.

**Comment by yarrumretep** [comment]
This is strange.  I just walked through this on Rinkeby and, indeed, rinkeby.etherscan.io says there is no code there.  However, if I do the same steps on Kovan, the deployed clone is shown on kovan.etherscan.io.  I suspect this may be a rinkeby.etherscan.io issue.  

If you use remix to interface with the contract "at"  the generated address, your Rinkeby clone works as expected (as does mine).  This further supports the theory that the issue is with etherscan's display of the deployed address.

If you feel this resolves your question, please close this ticket.  Otherwise, feel free to ping back.

**Comment by genkifs** [comment]
Interesting.  Hopefully the main net is more kovan like than rinkeby like.   However, it sounds like it's not your issue.  Thanks for looking.
